# Generated by Django 5.0.3 on 2024-05-19 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='avatar',
        ),
    ]
