# Generated by Django 5.0.3 on 2024-05-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_article_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/%Y%m%d/'),
        ),
    ]
